server:
  port: 8081

spring:
  cloud:
    gateway:
      discovery:
        # Habilita la búsqueda de servicios por nombre en Eureka
        locator:
          enabled: true
          
      routes:
        # Regla 1: MOVIE-SERVICE (Para /api/movies)
        - id: movie-service-route
          uri: lb://MOVIE-SERVICE
          predicates:
            - Path=/api/movies/**

        # Regla 2: BOOKING-SERVICE 
        # (Esta es la regla que faltaba/estaba mal, corrige el error 404)
        - id: booking-service-route
          uri: lb://BOOKING-SERVICE
          predicates:
            - Path=/api/bookings/**
