version: '3.8'

services:
  eureka-server:
    build: ./eureka-server
    ports:
      - "8761:8761"
    networks:
      - cinema-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  api-gateway:
    build: ./api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - eureka-server
    networks:
      - cinema-network
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/

  movie-service:
    build: ./movie-service
    ports:
      - "8081:8081"
    depends_on:
      - eureka-server
    networks:
      - cinema-network
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/

  booking-service:
    build: ./booking-service
    ports:
      - "8082:8082"
    depends_on:
      - eureka-server
    networks:
      - cinema-network
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/

  user-service:
    build: ./user-service
    ports:
      - "8083:8083"
    depends_on:
      - eureka-server
    networks:
      - cinema-network
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/

networks:
  cinema-network:
    driver: bridge
